---
# tasks file for ec2_cloudwatch_instance_recovery_alarm

- name: get facts of the ec2 instance
  ec2_instance_info:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "*{{ instance_name_tag }}*"
  register: ec2_instance_info_register


- name: set fact to create in memory inventory based on Instance Name and Instance ID
  set_fact:
    instance_ids: "{{ ec2_instance_info_register.instances | json_query(instance_id_query)  }}"

- name: set fact to create in memory inventory based on Instance Name and Instance ID
  set_fact:
    instance_name_list: "{{ ec2_instance_info_register.instances | json_query(instance_name_tag_query) | upper }}"


- name: create a combine list of instance ids and Instance Name
  set_fact:
    instance_list: "{{ instance_name_list | zip(instance_ids) | list }}"



- name: Create an alarm to recover a failed instance
  ec2_metric_alarm:
    state: present
    region: "{{ aws_region }}"
    profile: "{{ aws_profile }}"
    name: "EC2 {{ item[0] }} SYSTEM HEALTH CHECK FAILED AUTO-RECOVERY ALARM"
    metric: "StatusCheckFailed_System"
    namespace: "AWS/EC2"
    statistic: "Minimum"
    comparison: ">="
    threshold: 1.0
    period: 60
    evaluation_periods: 2
    unit: "Count"
    description: "This will recover an ec2 instance {{ item[0] }}  when SYSTEM HEALTH CHECK FAILED"
    dimensions: {"InstanceId": '{{item[1]}}' }
    alarm_actions: ["arn:aws:automate:{{ aws_region }}:ec2:recover"]
  with_items:
    - "{{ instance_list }}"
